### PR TITLE
completed the code restructure, I think

### PR DESCRIPTION
**Pull request by gellings**
Please review

### CODE REVIEW

**Comment by drinkdhmo** [comment]
@gellings Let's add the rosplane_sim package to this pull request as well.

**Review by drinkdhmo — COMMENTED** [review]
rosplane_sim needs an "include" subdirectory before it will compile.

**Review by drinkdhmo — APPROVED** [review]
Compiles fine once you manually add "include" dir to rosplane_sim.

**Review by dallinbriggs — APPROVED** [review]
Looks good. We'll just add that include folder as we get something to put in it.

**Pull request merged**
